@BASE_URL = http://localhost:3333
@RESOURCES = form

GET {{BASE_URL}}/{{RESOURCES}}

###
POST {{BASE_URL}}/{{RESOURCES}}
Content-Type: application/json

{
  "name": "teste2",
  "email": "teste@teste2.com",
  "entidade": "teste2"
}

###
DELETE {{BASE_URL}}/{{RESOURCES}}/<:id>

